# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b369b04a3f1b22099790e23d17d8af0a82289cefd3bbbcefdf0e9453c102bf6f11c947e58dccefabad97e6d8b11b1c8330d29e5e31bd5780285b9cc8e7be26

test:
  secret_key_base: d5c025ec249b88111957867f6eb0e6dcdf07d307b29e8e6eadb2e1f4bd48f5376079babc1f95c1fdeb914e47bd712d7b7e42fd3783a4368e00aad41e704de34d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
